<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MotorcycleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data to avoid duplication/clutter during development (optional, but good for clean state)
        // \App\Models\Motorcycle::truncate(); 

        $motorcycles = [
            // --- ENDURO ---
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 250 (172 FMM Design HS)',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 295990,
                'description' => 'Двигатель 172FMM, 21 л.с., воздушное охлаждение. Рама из хромомолибденового сплава. Для соревнований и жесткого бездорожья.',
                'image_url' => '/images/product_enduro_1.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая 1-N-2-3-4-5',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор Nibbi PE30',
                'weight' => 114,
                'tank_capacity' => 7.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 250 EFI Exclusive ARS',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300, 
                'power' => 25,
                'price' => 249900,
                'description' => 'Инжекторный двигатель PR300 с балансирным валом. Подвеска ARS с регулировками. ПТС.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая 1-N-2-3-4-5',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Инжектор',
                'weight' => 116,
                'tank_capacity' => 7.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 300 PRO EFI Exclusive',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 37,
                'price' => 383900,
                'description' => 'Топовый двигатель NC300-S (182MM) жидкостного охлаждения. 37 л.с. Для профессионалов.',
                'image_url' => '/images/product_enduro_1.png',
                'is_available' => true,
                'transmission' => '6-ступенчатая 1-N-2-3-4-5-6',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Инжектор',
                'weight' => 118,
                'tank_capacity' => 6.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 250 21/18',
                'type' => 'Enduro',
                'year' => 2023,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 205990,
                'description' => 'Классический эндуро на колесах 21/18. Подвеска KKE. Отличный выбор для начинающих.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 112,
                'tank_capacity' => 7.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'A7 Motard',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 26,
                'price' => 290000,
                'description' => 'Универсальный байк на дорожной резине. Идеален для города и легкого грунта.',
                'image_url' => '/images/product_enduro_1.png', 
                'is_available' => true,
                'transmission' => '6-ступенчатая',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Карбюратор',
                'weight' => 125,
                'tank_capacity' => 10.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 300 Carb Exclusive',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 31,
                'price' => 345000,
                'description' => 'Версия с карбюратором FCR. Максимальная отзывчивость на ручку газа. Для тех, кто любит классическую настройку.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '6-ступенчатая',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Карбюратор FCR35',
                'weight' => 117,
                'tank_capacity' => 6.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Enduro 250 FA',
                'type' => 'Enduro',
                'year' => 2023,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 245000,
                'description' => 'Надежный и доступный эндуро с двигателем воздушного охлаждения 172FMM. Отличный выбор для начинающих райдеров и лесных прогулок.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 114,
                'tank_capacity' => 7.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'A8 300 Carb',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 31,
                'price' => 310000,
                'description' => 'Легкий и мощный эндуро. Алюминиевая рама, топовая подвеска. Отличный баланс веса и мощности.',
                'image_url' => '/images/product_enduro_1.png',
                'is_available' => true,
                'transmission' => '6-ступенчатая',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Карбюратор',
                'weight' => 110,
                'tank_capacity' => 6.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'FX 250 Basic',
                'type' => 'Enduro',
                'year' => 2023,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 210000,
                'description' => 'Простой и надежный мотоцикл для дачи и леса. Стальная рама, электростартер, фара. Минимум обслуживания.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 115,
                'tank_capacity' => 6.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'LX 300',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 26,
                'price' => 275000,
                'description' => 'Полноразмерный эндуро с двигателем 177MM. Водяное охлаждение, 6 передач. Для уверенных пользователей.',
                'image_url' => '/images/product_enduro_1.png',
                'is_available' => true,
                'transmission' => '6-ступенчатая',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Карбюратор',
                'weight' => 120,
                'tank_capacity' => 7.5,
            ],
             [
                'brand' => 'Avantis',
                'model' => 'Enduro 450 PRO',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 450,
                'power' => 45,
                'price' => 480000,
                'description' => 'Монстр бездорожья. 450 кубов, огромный момент. Только для опытных райдеров. Не прощает ошибок.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Инжектор',
                'weight' => 122,
                'tank_capacity' => 8.0,
            ],
             [
                'brand' => 'BSE',
                'model' => 'Z3 250',
                'type' => 'Enduro',
                'year' => 2024,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 235000,
                'description' => 'Сбалансированный эндуро для любителей. Крепкая рама, качественный пластик.',
                'image_url' => '/images/product_enduro_1.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 113,
                'tank_capacity' => 6.5,
            ],
             [
                'brand' => 'Motoland',
                'model' => 'XT 250 ST',
                'type' => 'Enduro',
                'year' => 2023,
                'engine_capacity' => 250,
                'power' => 21,
                'price' => 195000,
                'description' => 'Бюджетный вариант для легкого эндуро. Простота конструкции и доступность запчастей.',
                'image_url' => '/images/product_enduro_2.png',
                'is_available' => true,
                'transmission' => '5-ступенчатая',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 115,
                'tank_capacity' => 7.0,
            ],

            // --- ATV (Quads) ---
            [
                'brand' => 'Avantis',
                'model' => 'Optima 200 Premium',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 200,
                'power' => 16,
                'price' => 259990,
                'description' => 'Премиальная комплектация. Балансирный вал, масляное охлаждение, литые диски.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор D-N-R',
                'cooling' => 'Масляное',
                'fuel_system' => 'Карбюратор',
                'weight' => 180,
                'tank_capacity' => 5.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Optima 200 Lux',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 200,
                'power' => 16,
                'price' => 239990,
                'description' => 'Надежный утилитарник. Вариатор, дисковые тормоза, светодиодная оптика.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор D-N-R',
                'cooling' => 'Масляное',
                'fuel_system' => 'Карбюратор',
                'weight' => 175,
                'tank_capacity' => 5.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'HS8 Shark 150 Premium',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 150,
                'power' => 13,
                'price' => 168990,
                'description' => 'Стильный дизайн, улучшенная подвеска. Идеален для подростков и легкого бездорожья.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор D-N-R',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 150,
                'tank_capacity' => 4.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Hunter 8 New Premium',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 125,
                'power' => 9,
                'price' => 153990,
                'description' => 'Обновленная версия 2024 года. Родительский контроль, автозапуск, защита рук.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                 'transmission' => 'Автомат F-N-R',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 120,
                'tank_capacity' => 3.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Terminator 300',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 24,
                'price' => 450000,
                'description' => 'Мощный полноприводный квадроцикл. Лебедка, литые диски, злая резина. Для охоты, рыбалки и экстремальных путешествий.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор L-H-N-R-P',
                'cooling' => 'Жидкостное',
                'fuel_system' => 'Инжектор',
                'weight' => 320,
                'tank_capacity' => 12.0,
            ],
             [
                'brand' => 'Avantis',
                'model' => 'Hunter 200 Big',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 200,
                'power' => 16,
                'price' => 230000,
                'description' => 'Утилитарный квадроцикл для всей семьи. Вариатор, багажники спереди и сзади, фаркоп. Пройдет там, где другие застрянут.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор D-N-R',
                'cooling' => 'Масляное',
                'fuel_system' => 'Карбюратор',
                'weight' => 180,
                'tank_capacity' => 5.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Mirage 125',
                'type' => 'ATV',
                'year' => 2023,
                'engine_capacity' => 125,
                'power' => 10,
                'price' => 145000,
                'description' => 'Подростковый квадроцикл со спортивным характером. Дисковые тормоза, ограничитель скорости, пульт родительского контроля.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Автомат F-N-R',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 125,
                'tank_capacity' => 4.0,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Hunter 8 New',
                'type' => 'ATV',
                'year' => 2023,
                'engine_capacity' => 125,
                'power' => 9,
                'price' => 135000,
                'description' => 'Обновленная версия популярного детского квадроцикла. LED оптика, электронный спидометр, автозапуск.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Автомат F-N-R',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 120,
                'tank_capacity' => 3.5,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Patriot 150',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 150,
                'power' => 13,
                'price' => 195000,
                'description' => 'Небольшой утилитарник для работы по хозяйству. Тяговитый мотор, большие колеса, прочный пластик.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор D-N-R',
                'cooling' => 'Воздушное',
                'fuel_system' => 'Карбюратор',
                'weight' => 160,
                'tank_capacity' => 5.0,
            ],
            [
                'brand' => 'Motoland',
                'model' => 'Wild Track X 200',
                'type' => 'ATV',
                'year' => 2023,
                'engine_capacity' => 200,
                'power' => 16,
                'price' => 185000,
                'description' => 'Доступный и проходимый квадроцикл. Хорошая альтернатива именитым брендам.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор',
                'cooling' => 'Масляное',
                'fuel_system' => 'Карбюратор',
                'weight' => 170,
                'tank_capacity' => 5.5,
            ],
             [
                'brand' => 'Yacota',
                'model' => 'Cabo 200',
                'type' => 'ATV',
                'year' => 2024,
                'engine_capacity' => 200,
                'power' => 17,
                'price' => 240000,
                'description' => 'Стильный и надежный. Богатая комплектация уже в базе.',
                'image_url' => '/images/category_atv.png',
                'is_available' => true,
                'transmission' => 'Вариатор',
                'cooling' => 'Масляное',
                'fuel_system' => 'Карбюратор',
                'weight' => 178,
                'tank_capacity' => 5.5,
            ],

            // --- PARTS & ACCESSORIES ---
            [
                'brand' => 'Zongshen',
                'model' => 'Двигатель NC300S',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 300,
                'power' => 0,
                'price' => 125000,
                'description' => 'Двигатель в сборе со всем навесным оборудованием. Оригинальная запчасть для мотоциклов Avantis Enduro PRO.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'Motul',
                'model' => '7100 10W40 1L',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 1800,
                'description' => 'Синтетическое моторное масло для 4-тактных двигателей. Обеспечивает максимальную защиту двигателя и коробки передач.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
             [
                'brand' => 'Avantis',
                'model' => 'Шлем Cross Carbon',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 15000,
                'description' => 'Легкий и прочный шлем из углеволокна. Сертификация ECE 22.05. Отличная вентиляция и обзор.',
                'image_url' => '/images/category_enduro.png',
                'is_available' => true,
            ],
            [
                'brand' => 'DID',
                'model' => 'Цепь 520 VX3',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 8500,
                'description' => 'Усиленная цепь X-Ring. Золотое покрытие. Долговечность и минимальное растяжение.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'Hiflo',
                'model' => 'Фильтр масляный HF116',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 450,
                'description' => 'Высококачественный фильтрующий элемент. Соответствует стандартам OEM.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'Renthal',
                'model' => 'Руль Twinwall 997',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 12000,
                'description' => 'Самый прочный руль в мире. Конструкция "труба в трубе". Выбор чемпионов.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'Kenda',
                'model' => 'Покрышка 120/100-18 K774',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 6500,
                'description' => 'Универсальная резина для среднего и мягкого грунта. Отличный зацеп и самоочистка.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'NGK',
                'model' => 'Свеча зажигания CR8E',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 800,
                'description' => 'Оригинальная свеча зажигания. Стабильная искра в любых условиях.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
            [
                'brand' => 'Avantis',
                'model' => 'Защита рук (комплект)',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 3500,
                'description' => 'Прочная алюминиевая защита рук с пластиковыми щитками. Защищает рычаги и руки от веток и камней.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
             [
                'brand' => 'Maxima',
                'model' => 'Смазка цепи Offroad',
                'type' => 'Parts',
                'year' => 2024,
                'engine_capacity' => 0,
                'power' => 0,
                'price' => 1200,
                'description' => 'Специальная смазка для внедорожной техники. Не смывается водой, не притягивает пыль.',
                'image_url' => '/images/category_parts.png',
                'is_available' => true,
            ],
        ];

        foreach ($motorcycles as $motorcycle) {
            \App\Models\Motorcycle::create($motorcycle);
        }
    }
}
